### PR TITLE
Optimize Duplicate checking queries

### LINKED ISSUE #264: v0.3.0 - Duplicate Checking not working
**Describe the bug**
Duplicate checking not working when message limit is set to 0

**To Reproduce**
Set duplicate limit to 0, duplicate time to 60. 
Submit multiple copies of the same message (more than 2) 
Only the first is filtered, subsequent messages are submitted

**Expected behavior**
All messages are filtered correctly

**Additional context**
This **MAY** have already been fixed with the commits i've made but intermittently still seeing the issue. 
Issue for visibility. 
This one should block release of 0.3.0 for now.

### PR DESCRIPTION
**Pull request by DanrwAU**
# Description

Possible fix for the duplicate message checking issues introduce in v0.3.0 and Knex when using multiple receivers. 

Doesn't Fix #264 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Running this in one of my production environments and seeing significantly better dupe checking. Would like feedback from others who were seeing this issue before calling it fixed though.

@s3m1s0n1c can you try this one out and see if your still seeing dupes?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated changelog.md with changes made

### CODE REVIEW

**Comment by davidmckenzie** [comment]
Interesting! I'm guessing that handles the fake-escaped characters a little better, unless there's some minor difference in whitespace between the two clients or something that's causing the dupes?

**Comment by DanrwAU** [comment]
Don't know why it worked, but postgres threw a hissy at the way i was doing it.... doing it this way seems to solve both issues *shrug*

**Comment by DanrwAU** [comment]
Dammit 
image

**Comment by s3m1s0n1c** [comment]
@DanrwAU Copy, Will try and give it a go as soon as I can..

Thanks

**Comment by DanrwAU** [comment]
Possibly got a little bit excited, i'm still seeing *some* nowhere near as many as before tho 
image

File: server/routes/api.js [hunk 1]
```diff
@@ -595,18 +595,18 @@ router.post('/messages', isLoggedIn, function(req, res, next) {
                           .as('temp_tab')
                     })
               })
-              .andWhere('message', 'like', message)
+              .andWhere('message', 'like', `%${message}%`)
```
Comment (DanrwAU) [inline server/routes/api.js]: Thinking about this further, do these even need to be like's? the whole idea is we want to match exact messages anyway. Thoughts?

Comment (davidmckenzie) [reply server/routes/api.js]: Yknow... I think you might be onto something. If it's = instead of LIKE then it might do less dodgy shit with special chars in the string. And from my Googling it appears there's more weirdness with LIKE too: https://stackoverflow.com/questions/543580/equals-vs-like

Comment (DanrwAU) [reply server/routes/api.js]: Pushed that change to my dupe heavy instance, looking good so far, see how we go

Comment (DanrwAU) [reply server/routes/api.js]: I'd be curious if it makes a difference for #256 as well

**Comment by DanrwAU** [comment]
I am definetly still getting some duplicates so not a great fix. I think these changes should stay in anyway but they don't have the desired effect 😭

**Comment by DanrwAU** [comment]
I think the dupes come down to the changes made with Knex, the previous driver was serializing and this one isn't. 

@marshyonline and I were discussing implementing a temp table and some sort of queueing as a possible solution but that sounds hard.... 😭
